version: '2'
services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "29092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  calculator:
    build: calculator
    container_name: calculator
    ports:
      - "8080:8080"

  deal:
    build: deal
    container_name: deal
    depends_on:
      - kafka
      - database
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/projectNeoflex
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sabrina
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - CALCULATOR_URL=http://calculator:8080
    links:
      - database

  database:
    image: postgres:13.12-alpine3.18
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=projectNeoflex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sabrina

  statement:
    build: statement
    container_name: statement
    hostname: statement
    ports:
      - "8082:8082"
    environment:
      - DEAL_URL=http://deal:8081

  dossier:
    build: dossier
    container_name: dossier
    depends_on:
      - kafka
      - deal
    ports:
      - "8083:8083"
    environment:
      - DEAL_URL=http://deal:8081
      - KAFKA_SERVER=kafka:9092
    env_file:
      - secret.env

  gateway:
    build: gateway
    container_name: gateway
    depends_on:
      - deal
      - statement
    ports:
      - "8084:8084"
    environment:
      - DEAL_URL=http://deal:8081
      - STATEMENT_URL=http://statement:8082