name: Java CI with Maven

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sabrina
          POSTGRES_DB: projectNeoflex
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build MS-statement with Maven
        run: mvn -B clean package --file ./statement/pom.xml

      - name: Build MS-calculator with Maven
        run: mvn -B clean package --file ./calculator/pom.xml

      - name: Build MS-deal with Maven
        run: mvn -B clean package --file ./deal/pom.xml

      - name: Build MS-dossier with Maven
        run: mvn -B clean package --file ./dossier/pom.xml

      - name: Build MS-gateway with Maven
        run: mvn -B clean package --file ./gateway/pom.xml
