name: Java CI with Maven

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sabrina
          POSTGRES_DB: projectNeoflex
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build MS-statement with Maven
        run: mvn -B clean package --file ./statement/pom.xml
      - name: Unit Tests Statement
        working-directory: statement
        run: mvn -B verify --file pom.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: statement
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and analyze statement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: statement
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RimmaAgabekova_credit-bank-app

      - name: Build MS-calculator with Maven
        run: mvn -B clean package --file ./calculator/pom.xml
      - name: Unit Tests Calculator
        working-directory: calculator
        run: mvn -B verify --file pom.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: calculator
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and analyze calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: calculator
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RimmaAgabekova_credit-bank-app

      - name: Build MS-deal with Maven
        run: mvn -B clean package --file ./deal/pom.xml
      - name: Unit Tests Deal
        working-directory: deal
        run: mvn -B verify --file pom.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: deal
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and analyze deal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: deal
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RimmaAgabekova_credit-bank-app

      - name: Build MS-dossier with Maven
        run: mvn -B clean package --file ./dossier/pom.xml
      - name: Build and analyze dossier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: dossier
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RimmaAgabekova_credit-bank-app

      - name: Build MS-gateway with Maven
        run: mvn -B clean package --file ./gateway/pom.xml
      - name: Build and analyze gateway
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: gateway
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RimmaAgabekova_credit-bank-app
